---
- name: Install rabbitmq
  apt:
    name: rabbitmq-server

# Configure rabbitmq to listen only on localhost.
# https://serverfault.com/a/319166
- name: Create rabbitmq-env.conf file
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
  notify:
    - restart rabbitmq

- name: Create rabbitmq.config file
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
  notify:
    - restart rabbitmq

- name: Ensure Rabbitmq is enabled
  service:
    name: rabbitmq-server
    enabled: yes
